version: "3.7"

services:
  db:
    container_name: plp_database
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: structure_db
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data

    labels:
      name: "Postgres SQL Database"

  web:
    container_name: plp_flask_app
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    expose: 
      - 5000
    depends_on: 
      - db
    environment:
      ENV_PORT: 5000

      FLASK_ENV: staging

      PG_HOSTNAME: localhost
      PG_PORT: 5432
      PG_USER: root
      PG_PASSWORD: password
      PG_DATABASE: structure_db
    volumes: 
      - ./:/flask_app
    command:  gunicorn --bind 0.0.0.0:5000  main
    labels:
      name: "Flask PLP App" 

  nginx:
    container_name: plp_nginx_server 
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - 80:80
      - 443:443
    depends_on: 
      - web
    labels: 
      name: "Nginx Reverse Proxy"

volumes:
  plpdb_volume: