
version: "3.3"
services: 
  mongo:
    image: mongo:latest
    container_name: plpdb_container
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    labels:
      name: "MongoDB Server"
    volumes: 
      - mongo_db:/var/lib/mongodb/data
volumes: 
  mongo_db: